all:
	gcc -g3 -o basic-api-example basic-api-example.c -L.. -lqdpll
	gcc -g3 -o basic-api-example2 basic-api-example2.c -L.. -lqdpll
	gcc -g3 -o basic-api-example3 basic-api-example3.c -L.. -lqdpll
	gcc -g3 -o basic-manual-selectors basic-manual-selectors.c -L.. -lqdpll

